### ISSUE TITLE
passing data only in case of certain events

### ISSUE THREAD

**Issue by somi37** [MarkEdmondson1234/ga-bq-stream#3]
hi i am trying to send data using this app. i have certain tags that send certain data. so currently only data being sent is of form submission tag. when form is submitted all the data i want is sent but not in other cases. HTML for submission tag is 
```
<script>
var bqArray = {};
 
var host = location.hostname;
var path = location.pathname;
var loc = host.concat(path);
  bqArray["clientId"] = ga.getAll()[0].get('clientId');
  bqArray["event"]= 'event';
 bqArray["location"] = loc;
   bqArray["metadata"] = "Page Visible";
  bqArray["contact"] = "submitted";
  bqArray["email"] = jQuery('[name="email"]').val();

  jQuery.post("https://bq-ml-site.appspot.com/bq-streamer", {"bq":JSON.stringify(bqArray)});

</script>
```
in other cases like pageview where there is no submission its not sending proper data.

**Comment by MarkEdmondson1234** [comment]
I would check the logs of AppEngine which should display what the payload received was and any errors if it didn't load them. 

If you can't garuntee all the fields each hit then you may also want to alter the big query load function to ignore known values
https://googlecloudplatform.github.io/google-cloud-python/stable/bigquery-table.html#google.cloud.bigquery.table.Table.insert_data

I am also assuming you have read the intro blog post about how to set up your BigQuery table etc. 
http://code.markedmondson.me/real-time-GTM-google-cloud-r-shiny-1/

**Comment by somi37** [comment]
thanks a lot its working now
